line-length = 100

select = [
  "E",
  "F",
  "B",
  "UP",
  "I",
  "E",
  "N",
  "YTT",
  "ANN",
  "S",
  "BLE",
  "A",
  "COM",
  "C4",
  "DTZ",
  "T10",
  "EM",
  "ISC",
  "ICN",
  "G",
  "PIE",
  "T20",
  "PYI",
  "PT",
  "RSE",
  "RET",
  "SLF",
  "SIM",
  "TID",
  "TCH",
  "INT",
  "ARG",
  "PTH",
]

ignore = ["S101", "ARG005", "ANN101"]