# Generated by Django 4.1.6 on 2023-04-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deadline', models.DateTimeField()),
                ('state', models.CharField(choices=[('new', 'New Task'), ('in development', 'In Development'), ('in qa', 'In Qa'), ('in code review', 'In Code Review'), ('ready for release', 'Ready For Release'), ('released', 'Released'), ('archived', 'Archived')], default='new', max_length=50)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'High'), (2, 'Low')], default=1)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['created_at'], name='main_task_created_f1bded_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['deadline'], name='main_task_deadlin_3ee647_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['state'], name='main_task_state_87eade_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['priority'], name='main_task_priorit_595117_idx'),
        ),
    ]
