# Generated by Django 4.1.6 on 2023-04-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_task_task_main_task_created_f1bded_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'high'), (2, 'low')], default=1),
        ),
    ]
