# Generated by Django 4.1.6 on 2023-04-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_tag_tag_main_tag_title_329360_idx_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('developer', 'Developer'), ('manager', 'Manager'), ('admin', 'Admin')], default='developer', max_length=255),
        ),
    ]
